# Generated by Django 6.0.2 on 2026-02-28 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('energy_type', models.CharField(choices=[('solar', '☀️ Solar'), ('wind', '💨 Wind'), ('biogas', '🌿 Biogas'), ('hydro', '💧 Hydro')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('total_funding_required', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_roi_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project_duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('planning', '📋 Planning'), ('funding', '💰 Seeking Funding'), ('active', '🚀 Active'), ('completed', '✅ Completed')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField()),
                ('project_document', models.FileField(blank=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_return', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', '✅ Active'), ('completed', '🎉 Completed'), ('withdrawn', '↩️ Withdrawn')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmentproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
